# Комиссия с обмена опыта (например, 0.1 означает 10% комиссии)
commission: 0.1

# Предмет для хранения опыта
item:
  material: BOOK
  custom_model_data: 0

# Настройки книги
book:
  display_name: "§6Хранитель опыта §7(§e%xp%§7)"
  glowing: true
  lore:
    - "§7Ранг: %tier_color%%tier_name%"
    - "§7Содержит §e%xp% §7опыта (§e%level% §7лвл)"
    - "§7Нажмите ПКМ, чтобы получить опыт"
  enchantments:
    - "unbreaking:1"

# Настройки кулдауна
cooldown: 5 # в секундах

# Максимальное количество опыта в одной книге
max_xp_per_book: 1000000

# Минимальное количество опыта для конвертации
min_xp_for_conversion: 100

# Звуковые эффекты
sound_effects:
  enabled: true
  create: ENTITY_EXPERIENCE_ORB_PICKUP
  use: ENTITY_PLAYER_LEVELUP

# Эффекты частиц
particle_effects: true

# Визуальные настройки
visual:
  use_action_bar: true  # Отображать короткие сообщения в ActionBar
  use_tier_system: true  # Использовать систему рангов для книг

# Настройки тиеров для книг
book_tiers:
  common:
    name: "Обычный"
    color: "§7"
    particle: "ENCHANTMENT_TABLE"
    min_xp: 0
    max_xp: 1000
  uncommon:
    name: "Необычный"
    color: "§a"
    particle: "VILLAGER_HAPPY"
    min_xp: 1001
    max_xp: 5000
  rare:
    name: "Редкий"
    color: "§9"
    particle: "END_ROD"
    min_xp: 5001
    max_xp: 20000
  epic:
    name: "Эпический"
    color: "§5"
    particle: "DRAGON_BREATH"
    min_xp: 20001
    max_xp: 50000
  legendary:
    name: "Легендарный"
    color: "§6"
    particle: "TOTEM"
    min_xp: 50001
    max_xp: 1000000

# Сообщения
messages:
  no_permission: "§cУ вас нет прав на использование этой команды!"
  cooldown: "@actionbar §cПодождите %time% секунд перед следующим использованием!"
  no_experience: "§cУ вас недостаточно опыта!"
  exchange_success: |
    §aКонвертация опыта:
    §7• Конвертировано: §e%xp_total% §7опыта
    §7• Комиссия (§6%commission_percent%§7): §e%commission_amount% §7опыта
    §7• Итого в книге: §e%xp_final% §7опыта
  use_success: "@actionbar §aВы получили §e%xp% §aопыта из книги!"
  invalid_book: "§cЭта книга была изменена и больше не действительна!"
  too_much_xp: "§cСлишком много опыта в книге! Максимум: §e%max_xp%"
  inventory_full: "§cОсвободите место в инвентаре!"
  not_enough_xp_for_conversion: "§cМинимальное количество опыта для конвертации: §e%min_xp%"
  help_message: |
    §6§l=== Помощь по плагину ExpChange ===
    §e/expchange §7- Конвертировать весь опыт в книгу
    §e/expchange <количество> exp §7- Конвертировать указанное количество опыта в книгу
    §e/expchange <количество> lvl §7- Конвертировать опыт для указанных уровней в книгу
    §e/expchange all §7- Конвертировать весь опыт в книгу
    §e/exphelp §7- Показать это сообщение
    §7§oПример: §e/expchange 1000 exp §7§oсоздаст книгу с 1000 опыта
    §7§oПример: §e/expchange 5 lvl §7§oсоздаст книгу с опытом для 5 уровней
    §6§l==============================